version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8001:8000"
    volumes:
    - ./:/app
    command: ./boot.sh
    depends_on:
    - db
    links:
    - db  
  db:
    image: postgres:latest